server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/organizationdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

